/* Generated from household-scenarios.csv. Do not edit by hand.
   Every figure traces to a row and column of the source file.
   Loaded via <script> tag - no fetch, works from file:// and GitHub Pages. */
window.BUDGET_DATA = {
  "meta": {
    "source_file": "household-scenarios.csv",
    "source_document": "2026-27 ACT Budget \u2014 household scenarios",
    "rates_column": "rates_pfesl_sfl_hl",
    "rates_column_note": "Bundled figure: general rates plus the Police, Fire and Emergency Services Levy, the Safer Families Levy and a further component abbreviated 'hl' in the source header. The source does not decompose it, so it must be described as 'rates and levies', never 'rates'.",
    "row_count": 18,
    "household_count": 9,
    "comparable_count": 6,
    "reconciliation": {
      "identity": "net_disposable_income = disposable_income - sum(charges) + sum(concessions)",
      "charge_columns": [
        "rates_pfesl_sfl_hl",
        "conveyance_duty",
        "vehicle_charges",
        "public_transport_fares",
        "utilities"
      ],
      "concession_columns": [
        "rates_pfesl_concession",
        "conveyance_duty_concession",
        "vehicle_concession",
        "public_transport_concession",
        "utilities_concession"
      ],
      "tolerance_dollars": 2,
      "rows_checked": 18,
      "rows_passed": 17,
      "rows_failed": 1,
      "failures": [
        {
          "id": 4,
          "suburb": "Cook",
          "year": "2025-26",
          "calculated": 55401,
          "published": 56300,
          "difference": -899,
          "note": "Published total exceeds the sum of its components by $899. Cause is not determinable from this file. Does not affect the rates column."
        }
      ]
    },
    "comparable_range": {
      "min_pct": -13.6,
      "max_pct": 13.2,
      "min_id": 4,
      "max_id": 9
    }
  },
  "households": [
    {
      "id": 1,
      "suburb": "Belconnen",
      "household": "Single, pensioner, in own unit, no car",
      "rates_2025_26": 1801,
      "rates_2026_27": 1739,
      "rates_change": -62,
      "rates_change_pct": -3.4,
      "comparable": true,
      "not_comparable_reason": null,
      "recon_status_2025_26": "pass",
      "recon_status_2026_27": "pass",
      "recon_difference_2025_26": 0.0,
      "recon_difference_2026_27": 0.0
    },
    {
      "id": 2,
      "suburb": "Braddon",
      "household": "Couple, pensioners, in own house, 2 cars, downsizing to unit in 2026-27",
      "rates_2025_26": 6493,
      "rates_2026_27": 2208,
      "rates_change": -4285,
      "rates_change_pct": -66.0,
      "comparable": false,
      "not_comparable_reason": "Downsizes from house to unit in 2026-27",
      "recon_status_2025_26": "pass",
      "recon_status_2026_27": "pass",
      "recon_difference_2025_26": 0.0,
      "recon_difference_2026_27": 0.0
    },
    {
      "id": 3,
      "suburb": "Banks",
      "household": "Single parent, first income quintile, in own house, 1 car, 1\u00a0child who catches the bus to school",
      "rates_2025_26": 2953,
      "rates_2026_27": 3022,
      "rates_change": 69,
      "rates_change_pct": 2.3,
      "comparable": true,
      "not_comparable_reason": null,
      "recon_status_2025_26": "pass",
      "recon_status_2026_27": "pass",
      "recon_difference_2025_26": 0.0,
      "recon_difference_2026_27": 0.0
    },
    {
      "id": 4,
      "suburb": "Cook",
      "household": "Single, fixed income retiree, in own house, 1 car",
      "rates_2025_26": 4990,
      "rates_2026_27": 4309,
      "rates_change": -681,
      "rates_change_pct": -13.6,
      "comparable": true,
      "not_comparable_reason": null,
      "recon_status_2025_26": "fail",
      "recon_status_2026_27": "pass",
      "recon_difference_2025_26": -899.0,
      "recon_difference_2026_27": 0.0
    },
    {
      "id": 5,
      "suburb": "Kingston",
      "household": "Single, second income quintile, in own unit, no car",
      "rates_2025_26": 2643,
      "rates_2026_27": 2758,
      "rates_change": 115,
      "rates_change_pct": 4.4,
      "comparable": true,
      "not_comparable_reason": null,
      "recon_status_2025_26": "pass",
      "recon_status_2026_27": "pass",
      "recon_difference_2025_26": 0.0,
      "recon_difference_2026_27": 0.0
    },
    {
      "id": 6,
      "suburb": "Turner",
      "household": "Single, third income quintile, 1 car, purchasing first unit in 2026-27",
      "rates_2025_26": 0,
      "rates_2026_27": 2559,
      "rates_change": 2559,
      "rates_change_pct": null,
      "comparable": false,
      "not_comparable_reason": "Purchases first unit in 2026-27 (no rates in 2025-26)",
      "recon_status_2025_26": "pass",
      "recon_status_2026_27": "pass",
      "recon_difference_2025_26": 0.0,
      "recon_difference_2026_27": 0.0
    },
    {
      "id": 7,
      "suburb": "Wright",
      "household": "Couple, third income quintile, 2 cars, first time buying house in 2026-27, 1 child who catches bus to school",
      "rates_2025_26": 0,
      "rates_2026_27": 4061,
      "rates_change": 4061,
      "rates_change_pct": null,
      "comparable": false,
      "not_comparable_reason": "Purchases first house in 2026-27 (no rates in 2025-26)",
      "recon_status_2025_26": "pass",
      "recon_status_2026_27": "pass",
      "recon_difference_2025_26": 0.0,
      "recon_difference_2026_27": 0.0
    },
    {
      "id": 8,
      "suburb": "Ainslie",
      "household": "Couple, fourth income quintile, in own house, 2 cars, 1 school child and 1 tertiary student who catch the bus",
      "rates_2025_26": 6144,
      "rates_2026_27": 6642,
      "rates_change": 498,
      "rates_change_pct": 8.1,
      "comparable": true,
      "not_comparable_reason": null,
      "recon_status_2025_26": "pass",
      "recon_status_2026_27": "pass",
      "recon_difference_2025_26": 0.0,
      "recon_difference_2026_27": 0.0
    },
    {
      "id": 9,
      "suburb": "Forrest",
      "household": "Couple, fifth income quintile, in own house, 2 cars, 2 children who catch the bus to school",
      "rates_2025_26": 15789,
      "rates_2026_27": 17872,
      "rates_change": 2083,
      "rates_change_pct": 13.2,
      "comparable": true,
      "not_comparable_reason": null,
      "recon_status_2025_26": "pass",
      "recon_status_2026_27": "pass",
      "recon_difference_2025_26": 0.0,
      "recon_difference_2026_27": 0.0
    }
  ],
  "rows": [
    {
      "id": 1,
      "suburb": "Belconnen",
      "household": "Single, pensioner, in own unit, no car",
      "year": "2025-26",
      "disposable_income": 29900,
      "rates_pfesl_sfl_hl": 1801,
      "conveyance_duty": 0,
      "vehicle_charges": 0,
      "public_transport_fares": 1411,
      "utilities": 4248,
      "rates_pfesl_concession": 865,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 0,
      "public_transport_concession": 706,
      "utilities_concession": 800,
      "net_disposable_income": 24811,
      "change": null,
      "recon_calculated": 24811,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 1,
      "suburb": "Belconnen",
      "household": "Single, pensioner, in own unit, no car",
      "year": "2026-27",
      "disposable_income": 31200,
      "rates_pfesl_sfl_hl": 1739,
      "conveyance_duty": 0,
      "vehicle_charges": 0,
      "public_transport_fares": 1665,
      "utilities": 4570,
      "rates_pfesl_concession": 883,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 0,
      "public_transport_concession": 835,
      "utilities_concession": 800,
      "net_disposable_income": 25744,
      "change": 933,
      "recon_calculated": 25744,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 2,
      "suburb": "Braddon",
      "household": "Couple, pensioners, in own house, 2 cars, downsizing to unit in 2026-27",
      "year": "2025-26",
      "disposable_income": 45000,
      "rates_pfesl_sfl_hl": 6493,
      "conveyance_duty": 0,
      "vehicle_charges": 1434,
      "public_transport_fares": 0,
      "utilities": 6125,
      "rates_pfesl_concession": 865,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 1114,
      "public_transport_concession": 0,
      "utilities_concession": 800,
      "net_disposable_income": 33727,
      "change": null,
      "recon_calculated": 33727,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 2,
      "suburb": "Braddon",
      "household": "Couple, pensioners, in own house, 2 cars, downsizing to unit in 2026-27",
      "year": "2026-27",
      "disposable_income": 47100,
      "rates_pfesl_sfl_hl": 2208,
      "conveyance_duty": 10568,
      "vehicle_charges": 1540,
      "public_transport_fares": 0,
      "utilities": 6510,
      "rates_pfesl_concession": 883,
      "conveyance_duty_concession": 10568,
      "vehicle_concession": 1217,
      "public_transport_concession": 0,
      "utilities_concession": 800,
      "net_disposable_income": 39742,
      "change": 6015,
      "recon_calculated": 39742,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 3,
      "suburb": "Banks",
      "household": "Single parent, first income quintile, in own house, 1 car, 1\u00a0child who catches the bus to school",
      "year": "2025-26",
      "disposable_income": 35800,
      "rates_pfesl_sfl_hl": 2953,
      "conveyance_duty": 0,
      "vehicle_charges": 717,
      "public_transport_fares": 937,
      "utilities": 6125,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 505,
      "public_transport_concession": 468,
      "utilities_concession": 800,
      "net_disposable_income": 26841,
      "change": null,
      "recon_calculated": 26841,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 3,
      "suburb": "Banks",
      "household": "Single parent, first income quintile, in own house, 1 car, 1\u00a0child who catches the bus to school",
      "year": "2026-27",
      "disposable_income": 37000,
      "rates_pfesl_sfl_hl": 3022,
      "conveyance_duty": 0,
      "vehicle_charges": 770,
      "public_transport_fares": 1084,
      "utilities": 6510,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 555,
      "public_transport_concession": 542,
      "utilities_concession": 800,
      "net_disposable_income": 27511,
      "change": 670,
      "recon_calculated": 27511,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 4,
      "suburb": "Cook",
      "household": "Single, fixed income retiree, in own house, 1 car",
      "year": "2025-26",
      "disposable_income": 65300,
      "rates_pfesl_sfl_hl": 4990,
      "conveyance_duty": 0,
      "vehicle_charges": 717,
      "public_transport_fares": 0,
      "utilities": 4248,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 56,
      "public_transport_concession": 0,
      "utilities_concession": 0,
      "net_disposable_income": 56300,
      "change": null,
      "recon_calculated": 55401,
      "recon_difference": -899,
      "recon_status": "fail"
    },
    {
      "id": 4,
      "suburb": "Cook",
      "household": "Single, fixed income retiree, in own house, 1 car",
      "year": "2026-27",
      "disposable_income": 68100,
      "rates_pfesl_sfl_hl": 4309,
      "conveyance_duty": 0,
      "vehicle_charges": 770,
      "public_transport_fares": 0,
      "utilities": 4573,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 61,
      "public_transport_concession": 0,
      "utilities_concession": 0,
      "net_disposable_income": 58509,
      "change": 2208,
      "recon_calculated": 58509,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 5,
      "suburb": "Kingston",
      "household": "Single, second income quintile, in own unit, no car",
      "year": "2025-26",
      "disposable_income": 61200,
      "rates_pfesl_sfl_hl": 2643,
      "conveyance_duty": 0,
      "vehicle_charges": 0,
      "public_transport_fares": 1411,
      "utilities": 4248,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 0,
      "public_transport_concession": 0,
      "utilities_concession": 0,
      "net_disposable_income": 52898,
      "change": null,
      "recon_calculated": 52898,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 5,
      "suburb": "Kingston",
      "household": "Single, second income quintile, in own unit, no car",
      "year": "2026-27",
      "disposable_income": 63200,
      "rates_pfesl_sfl_hl": 2758,
      "conveyance_duty": 0,
      "vehicle_charges": 0,
      "public_transport_fares": 1665,
      "utilities": 4573,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 0,
      "public_transport_concession": 0,
      "utilities_concession": 0,
      "net_disposable_income": 54204,
      "change": 1306,
      "recon_calculated": 54204,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 6,
      "suburb": "Turner",
      "household": "Single, third income quintile, 1 car, purchasing first unit in 2026-27",
      "year": "2025-26",
      "disposable_income": 81600,
      "rates_pfesl_sfl_hl": 0,
      "conveyance_duty": 0,
      "vehicle_charges": 717,
      "public_transport_fares": 0,
      "utilities": 4248,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 0,
      "public_transport_concession": 0,
      "utilities_concession": 0,
      "net_disposable_income": 76635,
      "change": null,
      "recon_calculated": 76635,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 6,
      "suburb": "Turner",
      "household": "Single, third income quintile, 1 car, purchasing first unit in 2026-27",
      "year": "2026-27",
      "disposable_income": 84200,
      "rates_pfesl_sfl_hl": 2559,
      "conveyance_duty": 14456,
      "vehicle_charges": 770,
      "public_transport_fares": 0,
      "utilities": 4573,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 14456,
      "vehicle_concession": 0,
      "public_transport_concession": 0,
      "utilities_concession": 0,
      "net_disposable_income": 76298,
      "change": -337,
      "recon_calculated": 76298,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 7,
      "suburb": "Wright",
      "household": "Couple, third income quintile, 2 cars, first time buying house in 2026-27, 1 child who catches bus to school",
      "year": "2025-26",
      "disposable_income": 163100,
      "rates_pfesl_sfl_hl": 0,
      "conveyance_duty": 0,
      "vehicle_charges": 1434,
      "public_transport_fares": 937,
      "utilities": 6125,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 0,
      "public_transport_concession": 468,
      "utilities_concession": 0,
      "net_disposable_income": 155072,
      "change": null,
      "recon_calculated": 155072,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 7,
      "suburb": "Wright",
      "household": "Couple, third income quintile, 2 cars, first time buying house in 2026-27, 1 child who catches bus to school",
      "year": "2026-27",
      "disposable_income": 168400,
      "rates_pfesl_sfl_hl": 4061,
      "conveyance_duty": 48358,
      "vehicle_charges": 1540,
      "public_transport_fares": 1084,
      "utilities": 6510,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 48358,
      "vehicle_concession": 0,
      "public_transport_concession": 542,
      "utilities_concession": 0,
      "net_disposable_income": 155747,
      "change": 675,
      "recon_calculated": 155747,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 8,
      "suburb": "Ainslie",
      "household": "Couple, fourth income quintile, in own house, 2 cars, 1 school child and 1 tertiary student who catch the bus",
      "year": "2025-26",
      "disposable_income": 210100,
      "rates_pfesl_sfl_hl": 6144,
      "conveyance_duty": 0,
      "vehicle_charges": 1434,
      "public_transport_fares": 2298,
      "utilities": 7981,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 0,
      "public_transport_concession": 1149,
      "utilities_concession": 0,
      "net_disposable_income": 193392,
      "change": null,
      "recon_calculated": 193392,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 8,
      "suburb": "Ainslie",
      "household": "Couple, fourth income quintile, in own house, 2 cars, 1 school child and 1 tertiary student who catch the bus",
      "year": "2026-27",
      "disposable_income": 217000,
      "rates_pfesl_sfl_hl": 6642,
      "conveyance_duty": 0,
      "vehicle_charges": 1540,
      "public_transport_fares": 2337,
      "utilities": 8429,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 0,
      "public_transport_concession": 1168,
      "utilities_concession": 0,
      "net_disposable_income": 199220,
      "change": 5828,
      "recon_calculated": 199220,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 9,
      "suburb": "Forrest",
      "household": "Couple, fifth income quintile, in own house, 2 cars, 2 children who catch the bus to school",
      "year": "2025-26",
      "disposable_income": 311900,
      "rates_pfesl_sfl_hl": 15789,
      "conveyance_duty": 0,
      "vehicle_charges": 1434,
      "public_transport_fares": 1874,
      "utilities": 7981,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 0,
      "public_transport_concession": 937,
      "utilities_concession": 0,
      "net_disposable_income": 285759,
      "change": null,
      "recon_calculated": 285759,
      "recon_difference": 0,
      "recon_status": "pass"
    },
    {
      "id": 9,
      "suburb": "Forrest",
      "household": "Couple, fifth income quintile, in own house, 2 cars, 2 children who catch the bus to school",
      "year": "2026-27",
      "disposable_income": 322000,
      "rates_pfesl_sfl_hl": 17872,
      "conveyance_duty": 0,
      "vehicle_charges": 1540,
      "public_transport_fares": 2168,
      "utilities": 8429,
      "rates_pfesl_concession": 0,
      "conveyance_duty_concession": 0,
      "vehicle_concession": 0,
      "public_transport_concession": 1084,
      "utilities_concession": 0,
      "net_disposable_income": 293075,
      "change": 7316,
      "recon_calculated": 293075,
      "recon_difference": 0,
      "recon_status": "pass"
    }
  ]
};
